# Generated by Django 4.2.13 on 2024-08-14 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='admission_group',
            field=models.CharField(blank=True, choices=[('І-ша група з електробезпеки', 'I'), ('ІI-а група з електробезпеки', 'II'), ('ІII-ша група з електробезпеки', 'III'), ('ІV-а до 1000V група з електробезпеки', 'IV до 1kV'), ('ІV-а вище 1000V група з електробезпеки', 'IV вище 1kV'), ('V-а група з електробезпеки', 'V')], default='Не вибрано', max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cell_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Номер має бути '+38', потім код оператора, а потім ще 7 цифр номеру. Наприклад: +380501234567", regex='^\\+38(050|066|095|099|067|068|096|097|098|063|073|093|091)\\d{7}$')], verbose_name='Мобільний'),
        ),
    ]
