# Generated by Django 4.2.13 on 2024-10-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='admission_group',
            field=models.CharField(blank=True, choices=[('І-ша група з електробезпеки', 'I'), ('ІI-а група з електробезпеки', 'II'), ('ІII-тя група з електробезпеки', 'III'), ('ІV-а до 1000V група з електробезпеки', 'IV до 1kV'), ('ІV-а вище 1000V група з електробезпеки', 'IV вище 1kV'), ('V-а група з електробезпеки', 'V'), ('Не вибрано', 'Не вибрано')], default='Не вибрано', max_length=130, null=True),
        ),
    ]
