# Generated by Django 4.2.13 on 2024-09-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_chat_id',
        ),
    ]
