# Generated by Django 4.2.13 on 2024-10-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Engineer', 'Інженер'), ('Electrician', 'Електрик')], default='Electrician', max_length=15),
        ),
    ]
