# Generated by Django 4.2.13 on 2024-08-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('substation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorControlCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MCC-1', 'Motor Control Center 1'), ('MCC-2', 'Motor Control Center 2'), ('MCC-3', 'Motor Control Center 3'), ('MCC-4', 'Motor Control Center 4'), ('MCC-5', 'Motor Control Center 5'), ('MCC-6', 'Motor Control Center 6'), ('MCC-7', 'Motor Control Center 7'), ('MCC-8', 'Motor Control Center 8'), ('MCC-9', 'Motor Control Center 9'), ('MCC-10', 'Motor Control Center 10'), ('MCC-11', 'Motor Control Center 11')], max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('substation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mccs', to='substation.substation')),
            ],
            options={
                'verbose_name': 'MCC',
                'verbose_name_plural': 'MCC',
            },
        ),
    ]
