# Generated by Django 4.2.13 on 2024-10-20 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_employee_admission_group'),
        ('task', '0003_usertask_alter_task_options_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AS', 'Призначено'), ('AC', 'Прийнято'), ('RE', 'Відхилено'), ('CO', 'Виконано')], default='AS', max_length=2)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Assignment Notes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.employee', verbose_name='Employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='task.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Employee Task Assignment',
                'verbose_name_plural': 'Employee Task Assignments',
                'unique_together': {('employee', 'task')},
            },
        ),
    ]
