# Generated by Django 4.2.13 on 2024-10-21 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_usertask_alter_task_options_alter_task_deadline_and_more'),
        ('node', '0004_alter_node_index_alter_nodemotor_unique_together'),
        ('users', '0002_alter_employee_admission_group'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetaskassignment',
            options={'verbose_name': 'Завдання працівника', 'verbose_name_plural': 'Завдання працівника'},
        ),
        migrations.RemoveField(
            model_name='employeetaskassignment',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='employeetaskassignment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='employeetaskassignment',
            name='status',
        ),
        migrations.AddField(
            model_name='employeetaskassignment',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='node.node', verbose_name='Вузол'),
        ),
        migrations.AlterField(
            model_name='employeetaskassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.employee', verbose_name='Співробітник'),
        ),
        migrations.AlterField(
            model_name='employeetaskassignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='task.task', verbose_name='Завдання'),
        ),
    ]
