# Generated by Django 4.2.13 on 2024-10-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_alter_node_index_alter_nodemotor_unique_together'),
        ('task', '0003_usertask_alter_task_options_alter_task_deadline_and_more'),
        ('users', '0002_alter_employee_admission_group'),
        ('assignments', '0002_alter_employeetaskassignment_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeTaskAssignment',
            new_name='TaskAssignment',
        ),
        migrations.RenameField(
            model_name='taskassignment',
            old_name='employee',
            new_name='doer',
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('doer', 'task')},
        ),
    ]
