# Generated by Django 4.2.13 on 2024-10-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('IP', 'In Progress'), ('CO', 'Completed'), ('CE', 'Canceled')], default='IP', max_length=2),
        ),
    ]
