# Generated by Django 4.2.13 on 2024-10-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('task.task',),
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PE', 'Призупинено'), ('IP', 'На виконанні'), ('CO', 'Закінчено'), ('CE', 'Скасовано')], default='IP', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(default='Завдання не поставлено.'),
        ),
    ]
