# Generated by Django 4.2.13 on 2024-08-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_tower', '0001_initial'),
        ('mcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField(default=0.0)),
                ('round_per_minute', models.PositiveSmallIntegerField(default=0)),
                ('connection', models.CharField(choices=[('▲', 'Triangle'), ('✳', 'Star')], default='▲', max_length=1)),
                ('amperage', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Двигун вузла',
                'verbose_name_plural': 'Двигуни',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SG', 'Засувка'), ('SG_', 'Засувка загружна'), ('SG__', 'Засувка вигружна'), ('CC', 'Kонвеєр'), ('E', 'Норія'), ('SMP', 'Пробовідбірник'), ('B', 'Вент. аспіраційний'), ('B_', 'Вент. аераційний'), ('S', 'Сепаратор очистки'), ('VL', 'Клапан перекидний'), ('VL3', 'Клапан 3-х ходовий'), ('F', 'Вентилятор'), ('RF', 'Вентилятор даховий'), ('SC', 'Шнек зачисний')], max_length=25)),
                ('index', models.CharField(max_length=10, unique=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='work_tower.worktowerlevel')),
                ('mcc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcc', to='mcc.motorcontrolcenter')),
                ('motor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='node.nodemotor')),
            ],
            options={
                'verbose_name': 'Вузол',
                'verbose_name_plural': 'Вузли',
            },
        ),
    ]
