# Generated by Django 4.2.13 on 2024-08-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(choices=[('Засувка', 'Засувка'), ('Засувка загружна', 'Засувка загружна'), ('Засувка вигружна', 'Засувка вигружна'), ('Kонвеєр', 'Kонвеєр'), ('Норія', 'Норія'), ('Пробовідбірник', 'Пробовідбірник'), ('Вент. аспіраційний', 'Вент. аспіраційний'), ('Вент. аераційний', 'Вент. аераційний'), ('Сепаратор очистки', 'Сепаратор очистки'), ('Клапан перекидний', 'Клапан перекидний'), ('Клапан 3-х ходовий', 'Клапан 3-х ходовий'), ('Вентилятор', 'Вентилятор'), ('Вентилятор даховий', 'Вентилятор даховий'), ('Шнек зачисний', 'Шнек зачисний')], max_length=25),
        ),
        migrations.AlterField(
            model_name='nodemotor',
            name='amperage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='nodemotor',
            name='power',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
