# Generated by Django 4.2.13 on 2024-09-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_alter_node_name_alter_nodemotor_amperage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodemotor',
            name='connection',
            field=models.CharField(choices=[('▲', 'Трикутник'), ('✳', 'Зірка')], default='▲', max_length=1),
        ),
    ]
