# Generated by Django 4.2.13 on 2024-09-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_alter_nodemotor_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='index',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='nodemotor',
            unique_together={('power', 'round_per_minute', 'connection', 'amperage')},
        ),
    ]
